### PR TITLE
feat: cosign support for release binaries

### PR DESCRIPTION
**Pull request by debendraoli**
Introduce a public key for cosigning and apply cosign to the binaries for enhanced security.

Also go version is bumped to `1.23`

### CODE REVIEW

**Comment by bcsainju** [comment]
can you add related docs for verification along with how it will be integrated in the docker images ?

**Comment by bcsainju** [comment]
Why does this differ completely from the earlier deployment security docs ?

**Comment by debendraoli** [comment]
> Why does this differ completely from the earlier deployment security docs ? https://github.com/icon-project/ICON-Projects-Planning/pull/513/files

That docs refers to the gpg one but the cosign is more robust and built-in support by goreleaser.

I'll work on documentation for cosign.

**Comment by bcsainju** [comment]
That is my point. When you create a document for one approach and then implement entirely different approach,both PRs shouldn't co-exist. Delete the one that has become obsolete.

**Review by bcsainju — APPROVED** [review]

**Review by bcsainju — APPROVED** [review]

**Pull request merged**
