### PR TITLE
fix: fallback to polling when RPC fails

### PR DESCRIPTION
**Pull request by debendraoli**
This pull request adds a fallback mechanism to switch to polling when the RPC fails. This ensures that the application can continue functioning even if the RPC connection is lost.

### CODE REVIEW

**Review by AntonAndell — COMMENTED** [review]
Not sure i understand, if the WS fails once will it poll infidelity?

**Comment by debendraoli** [comment]
> Not sure i understand, if the WS fails once will it poll infidelity?

https://github.com/icon-project/centralized-relay/blob/8cc2f151a16adc25d297fbb9ab533008b463d494/relayer/chains/evm/listener.go#L104

Here is the check and the next block is incremented sequently.

**Comment by debendraoli** [comment]
Polling happens only if there are missing blocks and stopped when reached to the latest block in that recovered period.

**Review by AntonAndell — APPROVED** [review]
Okeys sounds good, if you are confident i'd say create a release and we can test it out. Can't be much more problems. But lets only test in and push it to the lydia labs relay. Since the foundation one seem to be working fine

**Pull request merged**
